### Milestone 3: Feature Engineering and Model Tuning

This notebook focuses on enhancing our sentiment classification pipeline by introducing new features that capture deeper sentiment from review text, including Word2Vec embeddings and lexicon-based sentiment scores. We then apply hyperparameter tuning using PySpark’s MLlib to improve model performance on top of these engineered features. Both Logistic Regression and Random Forest models are evaluated, and their performance is compared using accuracy, F1 score, and confusion matrices.

In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, udf, count, when, isnan, isnull, mean, stddev, min, max, length, avg, expr, when, desc, concat, lit, coalesce
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DateType, FloatType
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from pyspark.sql import Window
import numpy as np
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml.feature import Word2Vec
from pyspark.ml.tuning import ParamGridBuilder, TrainValidationSplit
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from pyspark.ml.classification import LogisticRegressionModel
from pyspark.sql import Row

In [2]:
spark = SparkSession.builder \
    .appName("Amazon Reviews Training") \
    .config("spark.executor.memory", "4g") \
    .config("spark.driver.memory", "6g") \
    .config("spark.executor.cores", "1") \
    .config("spark.default.parallelism", "16") \
    .config("spark.sql.shuffle.partitions", "16") \
    .getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/04/06 22:52:34 INFO SparkEnv: Registering MapOutputTracker
25/04/06 22:52:34 INFO SparkEnv: Registering BlockManagerMaster
25/04/06 22:52:34 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
25/04/06 22:52:34 INFO SparkEnv: Registering OutputCommitCoordinator

In [3]:
amazon_dataset = spark.read.parquet("gs://final-project-bucket-amazon/processed/final_dataset.parquet")
print(f"Loaded {amazon_dataset.count()} reviews from parquet")

Loaded 18110850 reviews from parquet

In [4]:
print(f"Loaded {amazon_dataset.count()} rows")
amazon_dataset.printSchema()

Loaded 18110850 rows
root
 |-- helpful_ratio: double (nullable = true)
 |-- has_votes: integer (nullable = true)
 |-- vine_binary: integer (nullable = true)
 |-- verified_purchase_binary: integer (nullable = true)
 |-- product_category_vec: vector (nullable = true)
 |-- review_year: integer (nullable = true)
 |-- review_month: integer (nullable = true)
 |-- review_dayofweek: integer (nullable = true)
 |-- features: vector (nullable = true)
 |-- label: integer (nullable = true)

In [20]:
processed_df = spark.read.parquet("gs://final-project-bucket-amazon/processed/all_reviews_processed.parquet")

print(f"Loaded {processed_df.count()} reviews from all_reviews_processed.parquet")
processed_df.printSchema()

Loaded 18110850 reviews from all_reviews_processed.parquet
root
 |-- marketplace: string (nullable = true)
 |-- customer_id: string (nullable = true)
 |-- review_id: string (nullable = true)
 |-- product_id: string (nullable = true)
 |-- product_parent: string (nullable = true)
 |-- product_title: string (nullable = true)
 |-- product_category: string (nullable = true)
 |-- star_rating: integer (nullable = true)
 |-- helpful_votes: integer (nullable = true)
 |-- total_votes: integer (nullable = true)
 |-- vine: string (nullable = true)
 |-- verified_purchase: string (nullable = true)
 |-- review_headline: string (nullable = true)
 |-- review_body: string (nullable = true)
 |-- review_date: date (nullable = true)
 |-- helpful_ratio: double (nullable = true)
 |-- has_votes: integer (nullable = true)
 |-- review_length: integer (nullable = true)
 |-- combined_review_text: string (nullable = true)
 |-- combined_text_length: integer (nullable = true)
 |-- has_meaningful_content: integer (nullable = true)
 |-- vine_binary: integer (nullable = true)
 |-- verified_purchase_binary: integer (nullable = true)
 |-- product_category_index: double (nullable = true)
 |-- product_category_vec: vector (nullable = true)
 |-- review_year: integer (nullable = true)
 |-- review_month: integer (nullable = true)
 |-- review_dayofweek: integer (nullable = true)
 |-- words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- filtered_words: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- features: vector (nullable = true)
 |-- label: integer (nullable = true)

In [6]:
# Very simple sentiment lexicon
positive_words = {
    "good", "great", "excellent", "amazing", "love", "perfect", "fantastic", "wonderful", "satisfied", "awesome",
    "outstanding", "superb", "brilliant", "enjoyed", "best", "recommend", "liked", "positive", "delightful", "pleased",
    "happy", "impressive", "exceptional", "super", "flawless", "ideal", "appreciate", "beautiful", "worth", "solid"
}

negative_words = {
    "bad", "terrible", "awful", "poor", "disappointed", "hate", "worst", "horrible", "broken", "unusable",
    "boring", "cheap", "lame", "ridiculous", "waste", "problem", "issue", "delay", "slow", "negative",
    "useless", "difficult", "disgusting", "return", "refund", "inconvenient", "annoying", "frustrating", "low"
}


# UDF to calculate net sentiment score
def compute_sentiment_score(word_list):
    if not word_list:
        return 0
    pos_count = sum(1 for w in word_list if w in positive_words)
    neg_count = sum(1 for w in word_list if w in negative_words)
    return pos_count - neg_count

sentiment_score_udf = udf(compute_sentiment_score, IntegerType())

# Add the sentiment_score column
processed_df = processed_df.withColumn(
    "sentiment_score", sentiment_score_udf(col("filtered_words"))
)

# Preview the new feature
processed_df.select("combined_review_text", "filtered_words", "sentiment_score", "label").show(5, truncate=False)

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----+
|combined_review_text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |filtered_words                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |sentiment_score|label|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----+
|Satisfied-Again I found this book really interesting with 12 twelve short stories about Sabrina trying to find pieces for a new clock.FABULOUS.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |[satisfied-again, found, book, really, interesting, 12, twelve, short, stories, sabrina, trying, find, pieces, new, clock.fabulous.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |0              |1    |
|Bravo for The Lion's Game After reading Plum Island, there was no denying that John Corey would be back. It was a set up<br />I waited not very patiently for The Lion's Game only to be slightly disappointed. <br />What disappointed me are the following: Beth didn't return, the to frequent use of the F word; the  complete drop off of dialogue between Asad and John at the end; and oh, yes  the ending. This ending is a first for Mr. DeMille. <br />Put all that aside  though and the book was classic DeMille just not his best. <br />On the  positive side: The plot for the first 500 pages or so (some sleepless  nights); John's unstoppable banter (he has a quip for everyone); the  descriptive dialogue DeMille always uses (right down to the dirty laundry),  and the introduction and apparent staying power of Kate (read the book).  <br />I have read them all. If you are considering adding DeMille to your read  list consider starting with The Charm School or The General's Daughter.  Neither have John as the main character but are incredible reads. <br />Time  to wait impatiently for what John is up to next.|[bravo, lion's, game, reading, plum, island,, denying, john, corey, back., set, up<br, />i, waited, patiently, lion's, game, slightly, disappointed., <br, />what, disappointed, following:, beth, return,, frequent, use, f, word;, , complete, drop, dialogue, asad, john, end;, oh,, yes, , ending., ending, first, mr., demille., <br, />put, aside, , though, book, classic, demille, best., <br, />on, , positive, side:, plot, first, 500, pages, (some, sleepless, , nights);, john's, unstoppable, banter, (he, quip, everyone);, , descriptive, dialogue, demille, always, uses, (right, dirty, laundry),, , introduction, apparent, staying, power, kate, (read, book)., , <br, />i, read, all., considering, adding, demille, read, , list, consider, starting, charm, school, general's, daughter., , neither, john, main, character, incredible, reads., <br, />time, , wait, impatiently, john, next.]|0              |1    |
|Guide you to prepare TOEIC It is a useful book to prepare TOEIC test.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |[guide, prepare, toeic, useful, book, prepare, toeic, test.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |0              |0    |
|Can it get any better! I have read this book so many times that it is no longer possible to tell what the cover says!  Yet I keep coming back.  Dragonlance is the only fantasy series I truly find fascinating.  The characters in this book are a  true example of how creative the authors are.  One anyone who likes fantasy  novels must read this series!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |[get, better!, read, book, many, times, longer, possible, tell, cover, says!, , yet, keep, coming, back., , dragonlance, fantasy, series, truly, find, fascinating., , characters, book, , true, example, creative, authors, are., , one, anyone, likes, fantasy, , novels, must, read, series!]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |0              |1    |
|Lulled Along It was very easy to get in to this book. The short chapters could be consumed in a five minute break. The character development moved along, but I wanted more from the author. For a story that dealt with a lot of very  difficlt issues, mental illness, teenaged pregnancy, and marital breakup it  just moved along. Yet, it was a good story and one I would recommend.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |[lulled, along, easy, get, book., short, chapters, consumed, five, minute, break., character, development, moved, along,, wanted, author., story, dealt, lot, , difficlt, issues,, mental, illness,, teenaged, pregnancy,, marital, breakup, , moved, along., yet,, good, story, one, recommend.]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |1              |1    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----+
only showing top 5 rows

In [7]:
# Define a UDF to compute positive ratio
def compute_positive_ratio(words):
    if not words:
        return 0.0
    pos_count = sum(1 for w in words if w in positive_words)
    return float(pos_count) / len(words)

positive_ratio_udf = udf(compute_positive_ratio, FloatType())

# Apply to DataFrame
processed_df = processed_df.withColumn("positive_ratio", positive_ratio_udf(col("filtered_words")))

In [8]:
# UDF to compute negative ratio
def compute_negative_ratio(words):
    if not words:
        return 0.0
    neg_count = sum(1 for w in words if w in negative_words)
    return float(neg_count) / len(words)

negative_ratio_udf = udf(compute_negative_ratio, FloatType())

# Apply to DataFrame
processed_df = processed_df.withColumn("negative_ratio", negative_ratio_udf(col("filtered_words")))

In [9]:
# Sample 10% for training
w2v_sample_df = processed_df.sample(False, 0.02, seed=42)

# Use vectorSize = 50 for speed/memory optimization
w2v = Word2Vec(vectorSize=50, minCount=5, inputCol="filtered_words", outputCol="w2v_vector")
w2v_model = w2v.fit(w2v_sample_df)

# Transform full dataset with learned model
processed_df = w2v_model.transform(processed_df)

In [10]:
final_feature_cols = [
    "features",               # TF-IDF
    "product_category_vec",   # One-hot category
    "helpful_ratio",
    "has_votes",
    "vine_binary",
    "verified_purchase_binary",
    "review_year",
    "review_month",
    "review_dayofweek",
    "sentiment_score",
    "positive_ratio",
    "negative_ratio",
    "w2v_vector"
]



assembler = VectorAssembler(
    inputCols=final_feature_cols,
    outputCol="final_features"
)

# This will give you a DataFrame with all features + all original columns
processed_df = assembler.transform(processed_df)

final_df = processed_df.select("final_features", "label")
# Just check schema to confirm the final structure
final_df.printSchema()

# Look at a few rows (without truncating the full vector)
final_df.select("final_features", "label").show(3, truncate=False)
# Save as Parquet (efficient for vector data)
final_df.write.mode("overwrite").parquet("gs://final-project-bucket-amazon/processed/final_vectorized_df.parquet")

root
 |-- final_features: vector (nullable = true)
 |-- label: integer (nullable = true)

25/04/06 23:01:33 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|final_features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |label|
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|(10065,[263,393,585,1262,1927,2328,2383,2652,3634,4112,4967,5492,5619,6061,7510,10002,10005,10006,10009,10010,10011,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.8333333333333334,1.0,2000.0,3.0,1.0,0.10241140897075335,0.019327884229520958,0.04720593256254991,-0.009062730396787325,0.013162533504267533,0.0211305714212358,-0.009605400388439496,0.03814230939994256,0.06582373951872189,-0.07950411951169371,-0.18763717512289682,-0.032930208230391146,0.013807085280617078,-0.06360856878260772,0.13365970452626547,-0.044637992543478805,0.019724090412879983,0.048914493372042976,-0.017122185478607815,0.059413071473439535,0.13209438063204287,-0.043257126763152576,0.10675090849399567,0.02012087553739548,-0.02430543793986241,0.21305113954780003,0.02681412932773431,0.007184948772192001,0.10042678353687128,0.04699114213387171,0.12276637585212787,0.0448579711218675,-0.08732943870127201,0.016578463775416215,0.0577475948104014,0.04708788469433785,-0.08819469686519975,0.046509849528471627,0.09946174547076225,0.1134186298896869,0.16230959172050158,0.00875050649046898,0.010528567526489497,-0.038367373899867135,0.08899701471285273,0.050912006028617424,-0.007018500193953514,-0.07819000619153181,0.058509117489059764,0.0561541366080443])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |1    |
|(10065,[1,26,299,312,393,478,518,527,570,992,999,1106,1535,1637,2110,2263,2291,2408,2456,2575,2586,2630,2679,2716,2827,2926,2960,2969,3029,3056,3074,3372,3385,3586,3676,3783,3784,4266,4526,4561,4583,4638,4675,4867,4885,4970,5002,5040,5044,5065,5133,5183,5342,5369,5471,5477,5700,5844,6006,6043,6403,6405,6413,6494,6548,6777,6836,6856,7006,7050,7126,7158,7650,7938,8395,8577,8607,8616,8728,8858,8945,8975,9011,9050,9111,9205,9231,9277,9475,9477,9701,9749,9971,10002,10005,10006,10009,10010,10011,10013,10014,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,2000.0,3.0,3.0,0.008333333767950535,0.008333333767950535,0.08090343043198421,0.02742731002072105,-0.008932527214831983,0.04100382456090301,0.121697238231233,0.014814159594243393,-0.012502362160012126,-0.00839684165160482,-0.08862190523068421,-0.037145400202522674,-0.09036941900461291,0.030631855266013492,-0.017579616132813194,-0.14973467470069105,0.07682414336401659,-0.0772264603835841,-0.022557360717716315,-0.026933596404948426,-0.10747692396059089,-0.005181302747223527,0.13228903711618234,-0.10350622665137052,0.10628165597251306,0.07862708387741198,-0.026805706891658093,0.15867600347070643,0.01539253337541595,0.00952941175395002,0.04051352868894658,-0.0013172000374955435,0.02061433339258656,0.07072359567973763,0.03537480939412489,-0.05266356662323233,0.06574598775963143,0.02758430339793752,-0.05875336420625293,0.057630827706695226,-0.07394372352864594,0.04874265285616275,0.1118932100032301,-0.0036143097133996584,0.005137364680801208,-0.11198118231453312,0.09503571662935428,0.05162996264795462,0.04727593773083451,-0.007743499520195958,0.01266940672455045,0.06250770028564148])|1    |
|(10065,[181,393,1119,2286,3838,8960,10002,10005,10006,10009,10010,10011,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[2.0,1.0,1.0,2.0,1.0,1.0,1.0,0.4,1.0,2000.0,3.0,7.0,-0.04064916633069515,-0.07182342396117747,-0.06658105412498116,-0.19880581554025412,0.03420101571828127,0.01686387072550133,-0.08234915556386113,8.651334792375565E-5,-0.1450595783535391,-0.0401433392544277,-0.23173991963267326,-0.09233530436176807,0.23255465365946293,-0.09216976771131158,0.38685866445302963,-0.28090312890708447,-0.023453086148947477,0.19537136796861887,0.13437267462722957,0.10750993341207504,0.08789844042621553,-0.18420476641040295,0.13742322102189064,0.026194276986643672,-0.03815969359129667,0.36785190738737583,-0.032036619959399104,0.07083523040637374,-0.0012432800140231848,0.08009238261729479,-0.0383874149993062,-0.04672437906265259,0.05073745176196098,-0.004985884006600827,-0.17155732307583094,-0.0030123762553557754,-0.1477457955479622,0.1534529784694314,-0.13797448575496674,0.33044353872537613,-0.006007482763379812,-0.10342241544276476,0.12992640119045973,-0.12987988558597863,-0.12583567388355732,0.05310027068480849,-0.023078668862581253,0.06159741076407954,-0.053748553327750415,0.12184756621718407])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |0    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
only showing top 3 rows

25/04/06 23:01:38 WARN DAGScheduler: Broadcasting large task binary with size 1228.7 KiB

### Logistic Regression

In [12]:
# Split 85% for training + validation, 15% for final test
train_val_df, test_df = final_df.randomSplit([0.85, 0.15], seed=42)

# Split train_val into train (70%) and validation (15%)
train_df, val_df = train_val_df.randomSplit([0.8235, 0.1765], seed=42)

# Show counts
print(f"Train count: {train_df.count()}")
print(f"Validation count: {val_df.count()}")
print(f"Test count: {test_df.count()}")

Train count: 12674701

Validation count: 2717952

Test count: 2718197

In [13]:
# Count class instances
label_counts = train_df.groupBy("label").count().toPandas()

# Get label counts
neg_count = label_counts[label_counts['label'] == 0]['count'].values[0]
pos_count = label_counts[label_counts['label'] == 1]['count'].values[0]
total = neg_count + pos_count

# Inverse frequency
neg_weight = total / (2 * neg_count)
pos_weight = total / (2 * pos_count)

print(f"Class 0 (negative) weight: {neg_weight}")
print(f"Class 1 (positive) weight: {pos_weight}")

Class 0 (negative) weight: 2.149654961639414
Class 1 (positive) weight: 0.6515468421054255

In [14]:
train_df = train_df.withColumn("class_weight", when(col("label") == 0, lit(neg_weight)).otherwise(lit(pos_weight)))
val_df = val_df.withColumn("class_weight", when(col("label") == 0, lit(neg_weight)).otherwise(lit(pos_weight)))
test_df = test_df.withColumn("class_weight", when(col("label") == 0, lit(neg_weight)).otherwise(lit(pos_weight)))

In [15]:
# Define LR model with weightCol
lr = LogisticRegression(
    featuresCol="final_features",
    labelCol="label",
    predictionCol="prediction",
    weightCol="class_weight",
    maxIter=20
)

# Small grid for fast tuning
param_grid = ParamGridBuilder() \
    .addGrid(lr.regParam, [0.01, 0.1, 1.0]) \
    .addGrid(lr.elasticNetParam, [0.0, 0.5, 1.0]) \
    .build()

# Evaluator using F1 score
evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="f1")

# Train-validation split
tvs = TrainValidationSplit(
    estimator=lr,
    estimatorParamMaps=param_grid,
    evaluator=evaluator,
    trainRatio=0.8,
    seed=42
)

# Train on full train_df
tvs_model = tvs.fit(train_df)

25/04/03 06:36:15 WARN BlockManager: Asked to remove block broadcast_514_piece0, which does not exist

In [16]:
val_preds = tvs_model.transform(val_df)
test_preds = tvs_model.transform(test_df)

def evaluate(df, name):
    acc = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy").evaluate(df)
    f1 = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="f1").evaluate(df)
    print(f"{name} — Accuracy: {acc:.4f}, F1 Score: {f1:.4f}")

evaluate(val_preds, "Validation Set")
evaluate(test_preds, "Test Set")

Validation Set — Accuracy: 0.8684, F1 Score: 0.8741

Test Set — Accuracy: 0.8684, F1 Score: 0.8742

In [17]:
# Save the best model from TrainValidationSplit
tvs_model.bestModel.write().overwrite().save("gs://final-project-bucket-amazon/models/logistic_model_weighted_final")

In [18]:
test_preds.write.mode("overwrite").parquet("gs://final-project-bucket-amazon/results/logistic_preds_weighted.parquet")

25/04/03 07:27:24 WARN DAGScheduler: Broadcasting large task binary with size 1358.7 KiB

In [4]:
lr_model = LogisticRegressionModel.load("gs://final-project-bucket-amazon/models/logistic_model_weighted_final")

# Step 1: Get coefficients (1D vector of weights)
coefficients = lr_model.coefficients.toArray()

# Step 2: Get top N most important features (by absolute value)
importance_df = pd.DataFrame({
    "index": list(range(len(coefficients))),
    "coefficient": coefficients,
    "importance": abs(coefficients)
})

# Step 3: Show top 25 most important features
top_features = importance_df.sort_values("importance", ascending=False).head(25)
top_features

       index  coefficient  importance
10020  10020    -3.678188    3.678188
10014  10014    -3.437764    3.437764
10023  10023    -3.306025    3.306025
10044  10044    -3.073270    3.073270
10022  10022    -2.927749    2.927749
10050  10050    -2.747486    2.747486
10056  10056    -2.648972    2.648972
10040  10040    -2.592555    2.592555
10034  10034     2.339460    2.339460
10046  10046    -1.999165    1.999165
10021  10021     1.994184    1.994184
10030  10030     1.955682    1.955682
10016  10016     1.951458    1.951458
10027  10027     1.932147    1.932147
10032  10032    -1.886023    1.886023
10043  10043    -1.666810    1.666810
10053  10053     1.554058    1.554058
10035  10035    -1.543604    1.543604
10061  10061     1.445985    1.445985
10025  10025     1.393933    1.393933
10041  10041     1.384834    1.384834
10015  10015    -1.368363    1.368363
10013  10013     1.292402    1.292402
1243    1243     1.236205    1.236205
10057  10057     1.123821    1.123821

In [5]:
final_feature_cols = [
    "features",                 # HashingTF (10,000)
    "product_category_vec",     # one-hot category (let's say ~100)
    "helpful_ratio",            # scalar
    "has_votes",                # scalar
    "vine_binary",              # scalar
    "verified_purchase_binary", # scalar
    "review_year",              # scalar
    "review_month",             # scalar
    "review_dayofweek",         # scalar
    "sentiment_score",          # scalar
    "positive_ratio",           # scalar
    "w2v_vector"                # 50-dimensional dense vector
]

In [9]:
# Define sizes of each block
sizes = {
    "features": 10000,
    "product_category_vec": processed_df.select("product_category_vec").first()[0].size,
    "w2v_vector": 50
}

# Generate flat feature names
feature_names = []

# Add TF (hashed word features)
feature_names += [f"tf_{i}" for i in range(sizes["features"])]

# Add product category one-hot
feature_names += [f"category_{i}" for i in range(sizes["product_category_vec"])]

# Add scalar features (same order as in assembler)
feature_names += [
    "helpful_ratio",
    "has_votes",
    "vine_binary",
    "verified_purchase_binary",
    "review_year",
    "review_month",
    "review_dayofweek",
    "sentiment_score",
    "positive_ratio"
]

# Add w2v vector dims
feature_names += [f"w2v_{i}" for i in range(sizes["w2v_vector"])]

In [10]:
coeffs = lr_model.coefficients.toArray()

importance_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coeffs,
    "importance": abs(coeffs)
})

top_features = importance_df.sort_values("importance", ascending=False).head(25)
top_features

              feature  coefficient  importance
10020           w2v_6    -3.678188    3.678188
10014           w2v_0    -3.437764    3.437764
10023           w2v_9    -3.306025    3.306025
10044          w2v_30    -3.073270    3.073270
10022           w2v_8    -2.927749    2.927749
10050          w2v_36    -2.747486    2.747486
10056          w2v_42    -2.648972    2.648972
10040          w2v_26    -2.592555    2.592555
10034          w2v_20     2.339460    2.339460
10046          w2v_32    -1.999165    1.999165
10021           w2v_7     1.994184    1.994184
10030          w2v_16     1.955682    1.955682
10016           w2v_2     1.951458    1.951458
10027          w2v_13     1.932147    1.932147
10032          w2v_18    -1.886023    1.886023
10043          w2v_29    -1.666810    1.666810
10053          w2v_39     1.554058    1.554058
10035          w2v_21    -1.543604    1.543604
10061          w2v_47     1.445985    1.445985
10025          w2v_11     1.393933    1.393933
10041          w2v_27     1.384834    1.384834
10015           w2v_1    -1.368363    1.368363
10013  positive_ratio     1.292402    1.292402
1243          tf_1243     1.236205    1.236205
10057          w2v_43     1.123821    1.123821

In [3]:
# Load vectorized dataset from GCS
final_df = spark.read.parquet("gs://final-project-bucket-amazon/processed/final_vectorized_df.parquet")

# Check schema
final_df.printSchema()

# Quick peek at rows
final_df.show(5, truncate=False)

root
 |-- final_features: vector (nullable = true)
 |-- label: integer (nullable = true)

+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|final_features                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |label|
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
|(10065,[785,1340,1699,2682,3372,3457,3623,4049,5113,5931,6168,6177,6240,6866,7741,9661,9724,9868,10000,10008,10009,10010,10011,10012,10013,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2015.0,8.0,2.0,4.0,0.1666666716337204,0.15680347414066392,0.07360709530379002,-0.012426971069847543,-0.11291831832689543,-0.09844429527098933,-0.07242904593780015,-0.007701131204764048,0.12593659106642008,-0.11873510891261199,-0.10131917230319232,0.11983205362533529,-0.21845379782219726,-0.13495136114458242,0.11450138783159976,0.020916036485383906,0.055718714371323586,-0.10421936338146527,-0.03710744542574199,0.23446206375956535,-0.13153715394825363,0.037702097169434026,-0.10445387933092812,-0.06398387600590164,0.15785467073631781,-0.1206900462275371,0.030832725421835978,0.02586264822942515,0.1239297080455041,-0.046334540083383516,0.11392987566068769,-0.23479884567980963,0.20294487165908018,-0.11315342108719051,0.06502927234396338,0.13216795803358156,-0.22485075859973827,-0.2232879144139588,0.05388935188724038,-0.16607986856251955,-0.28790152724832296,0.14657735630559424,-0.11297988782947262,-0.1330177676475917,0.004401522222906351,-0.15033084080399323,-0.0698785706287405,0.16778693239515025,-0.25089035540198285,0.017810085924187053,-0.2817311484056214])|1    |
|(10065,[228,855,1738,1741,2635,2657,3267,3370,6136,6177,10000,10008,10009,10010,10011,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[3.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2015.0,8.0,1.0,-0.10719355170925458,-0.2077338678141435,-0.15431016087532043,0.1771910487363736,-0.10433269788821538,-0.12474448209007581,-0.09732710793614388,-0.03931971847390135,0.01327543891966343,0.1996746717952192,0.1421521026175469,0.007156057655811309,-0.027397955457369488,0.019412373083954056,0.05487258608142535,0.113569517309467,-0.03538651137302319,-0.07890044043306262,0.14320803278436264,0.025785359988609948,0.02785556986927986,-0.20575200021266937,-0.1717257495969534,0.13666298985481262,0.0539168942021206,0.3917549150685469,0.006120341022809346,0.052105345107459775,0.09636946891744931,0.05964123234152794,-0.10604581395164132,0.12754471770798168,0.07801034798224767,-0.21450352122386296,-0.058499010652303694,-0.267287902534008,-0.09955344684422016,0.018070825623969236,-0.15303628866871197,0.04438158621390661,0.23581772376783192,-0.13846396878361703,-0.14567114462455114,-0.09759000514944394,0.043267189214626946,0.2226488138238589,-0.12813604399561881,-0.09016195136743287,0.12455970592952023,0.030601628310978412])                                                                                                                      |1    |
|(10065,[932,3370,4242,5974,10000,10008,10009,10010,10011,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[1.0,1.0,1.0,1.0,1.0,1.0,2015.0,6.0,7.0,0.021995204500854015,0.11653933301568031,-0.3511444693431258,-0.23476607352495193,-0.035427242517471313,0.03862600028514862,-0.4132378427311778,-0.08535738382488489,-0.3190740942955017,0.05832763761281967,0.17240374005632475,0.12153372401371598,0.2361230067908764,0.13761678989976645,0.1849052645266056,0.17888517072424293,-0.019614222459495068,0.2096085473895073,0.2765549570322037,-0.24646407656837255,0.0722748152911663,0.08949539810419083,0.2711813524365425,-0.2072373339906335,0.0104553303681314,0.3093257041182369,0.06461355555802584,0.23394132778048515,0.21731363236904144,0.12315794080495834,-0.4645539182238281,0.19913619372528046,-0.4860690850764513,-0.32460286747664213,0.007952878251671791,-0.3181984070688486,-0.24208088498562574,-0.10255704820156097,-0.27070655673742294,-0.15011689066886902,0.35465040168492123,-0.10771525837481022,0.026268266141414642,0.07134053483605385,-0.3151498166844249,-0.25639707315713167,0.4987012594938278,-0.48298266623169184,-0.08806490898132324,-0.13165985536761582])                                                                                                                                                                                     |1    |
|(10065,[1770,2831,5347,6233,6664,10000,10008,10009,10010,10011,10012,10013,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[1.0,1.0,2.0,1.0,1.0,1.0,1.0,2015.0,5.0,3.0,2.0,0.3333333432674408,-0.2018810659646988,0.07360654355337222,0.15375810023397207,0.048362423976262406,-0.2642562432835499,0.0936961385111014,0.09422755513029793,0.18966475618071854,-0.01895153305182854,0.05243762334187825,0.11373934677491584,-0.1047617911050717,-0.17666569848855335,0.0849745124578476,-0.18232745428880054,-0.20949811907485127,-0.2793224484970172,0.04311696688334147,0.023937479282418885,-0.1073391648630301,0.3207608088850975,0.019883145888646443,-0.3229021752874056,0.13201582059264183,-0.013404631366332371,0.32584066689014435,-0.0512692021826903,0.026996228843927383,0.13245909847319126,-0.07460605228940645,-0.1985184053579966,0.10832107067108154,0.2734321138511101,-0.04024627586477436,0.3021759117643038,-0.4771422750006119,-0.3640102259814739,0.010563536236683527,-0.2944725835695863,0.07944071153178811,0.11423142813146114,-0.16837522263328233,-0.3440127968788147,-0.04646698695917924,0.1621092779872318,-0.022922012023627758,0.3129794026414553,-0.040815877417723335,0.18062745034694672,-0.1639903080649674])                                                                                                                                       |1    |
|(10065,[447,2682,4242,5974,7006,8185,10000,10008,10009,10010,10011,10012,10013,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064],[1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2015.0,6.0,6.0,1.0,0.1666666716337204,-0.12279648209611574,0.12485193088650703,-0.11090225400403142,0.1318755621711413,-0.12289355074365933,0.07195144022504488,-0.3072926426927248,0.21329717462261516,-0.30466098835070926,-0.11577320347229639,0.26328968442976475,-0.07362993506831117,0.025497255225976307,0.1105033764615655,0.06251057237386703,0.17606609190503755,-0.0017182230949401855,0.12674858805257827,0.1683992619315783,-0.0685993613830457,0.051980858513464526,0.257060245067502,0.11759478179737926,-0.233924667040507,0.027159993536770344,0.19528806318218508,0.042630241718143225,0.2725154633323351,0.16528022289276123,0.14636193526287872,-0.30996254427979386,0.05805159856875737,-0.31242805129537976,-0.2255502591530482,0.03193995418647925,-0.46319599201281864,-0.36084411789973575,-0.1532508349046111,-0.31617657095193863,-0.025822050248583157,0.3892678601356844,0.02011890709400177,-0.1582902626444896,-0.16797402128577232,-0.34599348111078143,-0.24969765621547896,0.5286734153827031,-0.25301693690319854,0.11614007432945073,-0.2151797090967496])                                                                                                                            |1    |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----+
only showing top 5 rows

### Random Forest

In [4]:
# Split into train+val and test
train_val_df, test_df = final_df.randomSplit([0.85, 0.15], seed=42)

# Split train_val into train and validation
train_df, val_df = train_val_df.randomSplit([0.8235, 0.1765], seed=42)  # ~70/15/15 split

print(f"Train count: {train_df.count()}")
print(f"Validation count: {val_df.count()}")
print(f"Test count: {test_df.count()}")

Train count: 12674472

Validation count: 2717994

Test count: 2718384

In [ ]:
# Count each class
label_counts = train_df.groupBy("label").count().toPandas()
neg_count = label_counts[label_counts['label'] == 0]['count'].values[0]
pos_count = label_counts[label_counts['label'] == 1]['count'].values[0]

# Calculate downsample ratio
downsample_ratio = neg_count / pos_count

# Downsample
neg_class_df = train_df.filter(col("label") == 0)
pos_class_df = train_df.filter(col("label") == 1)
pos_class_downsampled = pos_class_df.sample(withReplacement=False, fraction=downsample_ratio, seed=42)

# Create balanced training set
train_balanced_df = neg_class_df.union(pos_class_downsampled)

print(f"Balanced training data count: {train_balanced_df.count()}")

Balanced training data count: 5895167

In [6]:
# Define Random Forest
rf = RandomForestClassifier(
    featuresCol="final_features",
    labelCol="label",
    predictionCol="prediction",
    seed=42
)

# Define parameter grid
param_grid = ParamGridBuilder() \
    .addGrid(rf.numTrees, [30, 50]) \
    .addGrid(rf.maxDepth, [5, 10]) \
    .build()

# Evaluator
evaluator = MulticlassClassificationEvaluator(
    labelCol="label", predictionCol="prediction", metricName="f1"
)

# TrainValidationSplit
tvs = TrainValidationSplit(
    estimator=rf,
    estimatorParamMaps=param_grid,
    evaluator=evaluator,
    trainRatio=0.8,
    seed=42
)

# Train on balanced data
rf_model = tvs.fit(train_balanced_df)

25/04/05 00:28:56 WARN DAGScheduler: Broadcasting large task binary with size 1050.1 KiB
25/04/05 00:38:29 WARN DAGScheduler: Broadcasting large task binary with size 1071.3 KiB
25/04/05 00:40:02 WARN DAGScheduler: Broadcasting large task binary with size 1111.2 KiB
25/04/05 00:41:37 WARN DAGScheduler: Broadcasting large task binary with size 1191.1 KiB
25/04/05 00:43:15 WARN DAGScheduler: Broadcasting large task binary with size 1342.4 KiB
25/04/05 00:49:06 WARN DAGScheduler: Broadcasting large task binary with size 1050.1 KiB
25/04/05 00:58:32 WARN DAGScheduler: Broadcasting large task binary with size 1071.3 KiB
25/04/05 01:00:16 WARN DAGScheduler: Broadcasting large task binary with size 1111.2 KiB
25/04/05 01:02:01 WARN DAGScheduler: Broadcasting large task binary with size 1191.1 KiB
25/04/05 01:03:49 WARN DAGScheduler: Broadcasting large task binary with size 1342.4 KiB
25/04/05 01:05:41 WARN DAGScheduler: Broadcasting large task binary with size 1615.0 KiB
25/04/05 01:07:39 WARN DAGScheduler: Broadcasting large task binary with size 2.0 MiB
25/04/05 01:09:39 WARN DAGScheduler: Broadcasting large task binary with size 2.8 MiB
25/04/05 01:11:47 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
25/04/05 01:14:07 WARN DAGScheduler: Broadcasting large task binary with size 5.5 MiB
25/04/05 01:16:42 WARN DAGScheduler: Broadcasting large task binary with size 2.5 MiB
25/04/05 01:17:40 WARN DAGScheduler: Broadcasting large task binary with size 1059.4 KiB
25/04/05 01:27:17 WARN DAGScheduler: Broadcasting large task binary with size 1094.5 KiB
25/04/05 01:29:19 WARN DAGScheduler: Broadcasting large task binary with size 1161.0 KiB
25/04/05 01:31:24 WARN DAGScheduler: Broadcasting large task binary with size 1292.6 KiB
25/04/05 01:33:36 WARN DAGScheduler: Broadcasting large task binary with size 1539.8 KiB
25/04/05 01:36:46 WARN DAGScheduler: Broadcasting large task binary with size 1059.4 KiB
25/04/05 01:46:29 WARN DAGScheduler: Broadcasting large task binary with size 1094.5 KiB
25/04/05 01:48:33 WARN DAGScheduler: Broadcasting large task binary with size 1161.0 KiB
25/04/05 01:50:37 WARN DAGScheduler: Broadcasting large task binary with size 1292.6 KiB
25/04/05 01:52:49 WARN DAGScheduler: Broadcasting large task binary with size 1539.8 KiB
25/04/05 01:55:07 WARN DAGScheduler: Broadcasting large task binary with size 1980.5 KiB
25/04/05 01:57:34 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
25/04/05 02:00:13 WARN DAGScheduler: Broadcasting large task binary with size 3.9 MiB
25/04/05 02:03:11 WARN DAGScheduler: Broadcasting large task binary with size 5.8 MiB
25/04/05 02:06:31 WARN DAGScheduler: Broadcasting large task binary with size 8.5 MiB
25/04/05 02:10:15 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/05 02:20:40 WARN DAGScheduler: Broadcasting large task binary with size 1059.1 KiB
25/04/05 02:36:30 WARN DAGScheduler: Broadcasting large task binary with size 1094.2 KiB
25/04/05 02:39:06 WARN DAGScheduler: Broadcasting large task binary with size 1160.7 KiB
25/04/05 02:41:41 WARN DAGScheduler: Broadcasting large task binary with size 1292.3 KiB
25/04/05 02:44:27 WARN DAGScheduler: Broadcasting large task binary with size 1544.6 KiB
25/04/05 02:47:25 WARN DAGScheduler: Broadcasting large task binary with size 1998.5 KiB
25/04/05 02:50:32 WARN DAGScheduler: Broadcasting large task binary with size 2.7 MiB
25/04/05 02:53:53 WARN DAGScheduler: Broadcasting large task binary with size 4.0 MiB
25/04/05 02:57:32 WARN DAGScheduler: Broadcasting large task binary with size 5.9 MiB
25/04/05 03:01:38 WARN DAGScheduler: Broadcasting large task binary with size 8.8 MiB

In [ ]:
# Predictions
train_preds = rf_model.transform(train_df)
val_preds = rf_model.transform(val_df)
test_preds = rf_model.transform(test_df)

# Evaluation function
def evaluate(df, name):
    acc = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy").evaluate(df)
    f1 = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="f1").evaluate(df)
    print(f"{name} — Accuracy: {acc:.4f}, F1 Score: {f1:.4f}")

# Run evals
evaluate(train_preds, "Train Set")
evaluate(val_preds, "Validation Set")
evaluate(test_preds, "Test Set")

25/04/05 03:06:18 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/05 03:10:41 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB

Train Set — Accuracy: 0.7665, F1 Score: 0.7835

25/04/05 03:15:09 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/05 03:17:29 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB

Validation Set — Accuracy: 0.7662, F1 Score: 0.7831

25/04/05 03:19:44 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/05 03:21:53 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB

Test Set — Accuracy: 0.7668, F1 Score: 0.7837

In [8]:
# Save best model from TrainValidationSplit
rf_model.bestModel.write().overwrite().save("gs://final-project-bucket-amazon/models/rf_model_balanced")

In [11]:
logistic_test_preds = spark.read.parquet("gs://final-project-bucket-amazon/results/logistic_preds_weighted.parquet")

In [12]:
# Group and count label-prediction pairs
conf_matrix_df = logistic_test_preds.groupBy("label", "prediction").count().orderBy("label", "prediction")

# Show the result
conf_matrix_df.show()

+-----+----------+-------+
|label|prediction|  count|
+-----+----------+-------+
|    0|       0.0| 555643|
|    0|       1.0|  76720|
|    1|       0.0| 280936|
|    1|       1.0|1804898|
+-----+----------+-------+

In [13]:
conf_pivot_logistic = conf_matrix_df.groupBy("label") \
    .pivot("prediction", [0.0, 1.0]) \
    .sum("count") \
    .fillna(0) \
    .orderBy("label")

conf_pivot_logistic.show()

+-----+------+-------+
|label|   0.0|    1.0|
+-----+------+-------+
|    0|555643|  76720|
|    1|280936|1804898|
+-----+------+-------+

In [14]:
# Load the final trained RF model
rf_model = RandomForestClassificationModel.load("gs://final-project-bucket-amazon/models/rf_model_balanced")

In [15]:
# Load final vectorized dataset
final_df = spark.read.parquet("gs://final-project-bucket-amazon/processed/final_vectorized_df.parquet")

# Recreate split for test set
train_val_df, test_df = final_df.randomSplit([0.85, 0.15], seed=42)

In [16]:
test_preds = rf_model.transform(test_df)

In [17]:
# Group by label and prediction
conf_matrix = test_preds.groupBy("label", "prediction").count().orderBy("label", "prediction")
conf_matrix.show()

# Pivoted version for easier view
conf_matrix.groupBy("label").pivot("prediction", [0.0, 1.0]) \
    .sum("count").fillna(0).orderBy("label").show()

25/04/06 23:23:01 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/06 23:25:23 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB

+-----+----------+-------+
|label|prediction|  count|
+-----+----------+-------+
|    0|       0.0| 518550|
|    0|       1.0| 114379|
|    1|       0.0| 725032|
|    1|       1.0|1360433|
+-----+----------+-------+

25/04/06 23:25:24 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/06 23:27:34 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB
25/04/06 23:27:35 WARN DAGScheduler: Broadcasting large task binary with size 3.8 MiB

+-----+------+-------+
|label|   0.0|    1.0|
+-----+------+-------+
|    0|518550| 114379|
|    1|725032|1360433|
+-----+------+-------+

In [21]:
# This will give you the actual size of the one-hot encoded category vector
category_size = processed_df.select("product_category_vec").first()[0].size

In [22]:
# Start from the known order of your VectorAssembler
feature_names = [f"tf_{i}" for i in range(10000)]
feature_names += [f"category_{i}" for i in range(category_size)]
feature_names += [
    "helpful_ratio", "has_votes", "vine_binary", "verified_purchase_binary",
    "review_year", "review_month", "review_dayofweek",
    "sentiment_score", "positive_ratio", "negative_ratio"
]
feature_names += [f"w2v_{i}" for i in range(50)]

In [23]:
# Extract importancesfor random forest 
importances = rf_model.featureImportances.toArray()

# Trim feature_names if needed
if len(importances) < len(feature_names):
    feature_names = feature_names[:len(importances)]

# Convert to Spark DataFrame
importance_rows = [Row(feature=feature_names[i], importance=float(imp)) for i, imp in enumerate(importances)]
importance_df = spark.createDataFrame(importance_rows)

# Show top 25 features
importance_df.orderBy(col("importance").desc()).show(25, truncate=False)

+---------------+--------------------+
|feature        |importance          |
+---------------+--------------------+
|sentiment_score|0.05367280985327092 |
|w2v_29         |0.05176023077309377 |
|positive_ratio |0.03675677258412499 |
|negative_ratio |0.03600179805354796 |
|w2v_35         |0.034687276936365065|
|w2v_7          |0.03285298517130197 |
|w2v_9          |0.032250485917935466|
|w2v_42         |0.029854619477310572|
|w2v_30         |0.026276290201012558|
|w2v_5          |0.025808907219520887|
|w2v_24         |0.022997596170141195|
|tf_750         |0.02209018253299534 |
|w2v_39         |0.020374848886587797|
|w2v_47         |0.01836561000452036 |
|w2v_40         |0.017727467278299422|
|w2v_6          |0.016774450965335662|
|w2v_25         |0.0161242728245598  |
|w2v_17         |0.015563885567279117|
|w2v_14         |0.014030924574208332|
|w2v_16         |0.013840398378365705|
|tf_4012        |0.01375076848305279 |
|w2v_33         |0.01300283430778099 |
|w2v_38         |0.012794333734862379|
|w2v_15         |0.012724803594211794|
|tf_5925        |0.012303535656158545|
+---------------+--------------------+
only showing top 25 rows